version: "3"
services:
  myweb_image: # 빌드될 이미지명. 폴더명 + 이미지명으로 생성됨.
    container_name: myweb_con
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./ # 도커파일 위치 명시
    ports:
      - "8080:80" # port 맵핑
    stdin_open: true
