version: "3"
services:
  frontend: # 빌드될 이미지명. 폴더명 + 이미지명으로 생성됨.
    image: my-web:{$TAG}
    container_name: my-web-con
    build:
      dockerfile: Dockerfile # dockerfile이름
      context: ./ # 도커파일 위치 명시
    ports:
      - "80:80" # port 맵핑
    stdin_open: true
